=== kadisk/KADISKCorpRepo/VirtualDesk.Module/Webservices.layer/kadisk-ecosystem-monitoring.webservice/metadata/startup-params-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"port": {
			"type": "string",
			"pattern": "^[0-9]+$"
		},
		"serverName": {
			"type": "string"
		},
		"ecosystemDefaultsFileRelativePath": {
			"type": "string"
		},
		"instanceMonitoringManagerServiceStorageFilePath": {
			"type": "string"
		},
		"installDataDirPath":{
			"type": "string"
		}
	},
	"required": [
		"port",
		"serverName",
		"ecosystemDefaultsFileRelativePath",
		"instanceMonitoringManagerServiceStorageFilePath",
		"installDataDirPath"
	]
}

=== kadisk/KADISKCorpRepo/VirtualDesk.Module/Webservices.layer/kadisk-ecosystem-monitoring.webservice/metadata/startup-params.json
{
    "port":"8745",
    "serverName":"KadiskEcosystemMonitoringWebService",
    "ecosystemDefaultsFileRelativePath":"./config-files/ecosystem-defaults.json",
    "instanceMonitoringManagerServiceStorageFilePath": "/workspaces/databases/instance-monitoring-manager-service.sqlite",
    "installDataDirPath":"~/EcosystemData"
}
